# Generated by Django 5.2.7 on 2025-12-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, default='users/user-default.jpg', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users/user-default.jpg', null=True, upload_to='users'),
        ),
    ]
